added namespace to tankdrivetrain
Spikes-2212-Programming-Guild/SpikesLib2 pull request #141
Opened 2022-02-12 13:16 UTC by yutytuty

2022-02-12 13:18 UTC, OfriRosenbaum requested changes

2022-02-12 13:19 UTC, yutytuty commented on src/main/java/com/spikes2212/command/drivetrains/OdometryDrivetrain.java
> +    public OdometryDrivetrain(String namespaceName, MotorController left, MotorController right) {
wat

2022-02-12 13:24 UTC, OfriRosenbaum commented on src/main/java/com/spikes2212/command/drivetrains/OdometryDrivetrain.java
> +        super.periodic();
first call `getHandler().calculate()` and only then call the `super.periodic()`

2022-02-12 13:49 UTC, tal-sitton requested changes

2022-02-12 13:49 UTC, tal-sitton commented on src/main/java/com/spikes2212/command/drivetrains/TankDrivetrain.java
> +    public TankDrivetrain(MotorController left, MotorController right, String namespaceName) {
namespace first

2022-02-12 15:12 UTC, tal-sitton approved these changes

2022-02-12 15:12 UTC, tal-sitton requested changes

2022-02-12 15:12 UTC, tal-sitton commented on src/main/java/com/spikes2212/command/drivetrains/TankDrivetrain.java
> +
why blank line?

2022-02-15 20:26 UTC, tal-sitton approved these changes

2022-02-15 20:27 UTC, merged