added smart motor controller drivetrain
Spikes-2212-Programming-Guild/SpikesLib2 pull request #173
Opened 2023-01-12 17:46 UTC by Yoel-Perman-Brilliant

2023-01-12 17:46 UTC, Yoel-Perman-Brilliant commented
no trapezim yet

2023-01-12 22:01 UTC, OfriRosenbaum commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +        //is this good? it seems wrong
it's fine but you are calling the `getFPGATimestamp` many times, maybe save this as a variable at the start of the function (`time = Timer.getFPGATimestamp` and use time)

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +     * Constructs a new (generic) instance of {@link MoveSmartMotorControllerTankDrivetrain}.
remove generic

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +     * @param drivetrain          the {@link SmartMotorControllerGenericSubsystem} this command will run on
drivetrain

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +     * @param feedForwardSettings the loop's feed forward gains
loops'

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +     * @param controlMode         the loop's control mode (e.g. voltage, velocity, position...)
loops'

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +     *                            {@link SmartMotorControllerGenericSubsystem}'s left side to
drivetrain

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +     *                            {@link SmartMotorControllerGenericSubsystem}'s right side to
ditto

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrain.java
> +     * Updates any control loops running on the drivetrain.
drivetrain's motor controllers

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrainTrapezically.java
> + * A command that moves a {@link SmartMotorControllerTankDrivetrain} by running a trapezoid profile on its
by running trapezoid profile control loops on its master motor controllers

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/MoveSmartMotorControllerTankDrivetrainTrapezically.java
> + * A command that moves a {@link SmartMotorControllerTankDrivetrain} by running a trapezoid profile on its
by running trapezoid profile control loops on its master motor controllers

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/smartmotorcontrollersubsystem/MoveSmartMotorControllerSubsystem.java
>  public class MoveSmartMotorControllerSubsystem extends CommandBase {
Generic

2023-01-18 08:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/genericsubsystem/smartmotorcontrollersubsystem/CTRESmartMotorControllerGenericSubsystem.java
>   * @see MotorController
remove

2023-01-18 16:52 UTC, Spikes-2212 requested changes

2023-01-18 16:52 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/smartmotorcontrollerdrivetrain/CTRESmartMotorControllerDrivetrain.java
> +                if (leftMaster instanceof BaseTalon) {
right

2023-01-18 16:52 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/smartmotorcontrollerdrivetrain/MoveSmartMotorControllerTankDrivetrainTrapezically.java
> +     * @param trapezoidProfileSettings the trapezoid profile setting
settings

2023-01-18 16:52 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/smartmotorcontrollerdrivetrain/SparkMaxTankDrivetrain.java
> +     * The left {@link CANSparkMax} which run the loops.
runs

2023-01-18 16:52 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/smartmotorcontrollerdrivetrain/SparkMaxTankDrivetrain.java
> +     * The right {@link CANSparkMax} which run the loops.
runs

2023-01-18 16:52 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/smartmotorcontrollerdrivetrain/SparkMaxTankDrivetrain.java
> +     * @param rightSlave    an additional {@link CANSparkMax}s that follows the right master
remove s after sparkmax

2023-01-18 17:08 UTC, merged