created DoubleSolenoidSubsystem
Spikes-2212-Programming-Guild/SpikesLib2 pull request #193
Opened 2023-07-26 08:05 UTC by Spikes-2212

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant requested changes

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> + * A class that represents a double solenoid.
1. It represents a subsystem, not the solenoid itself.
2. B-I\a2

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    /**
Given a descriptive enough class documentation, this is unnecessary.

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +     * @return An {@link InstantCommand} that opens the solenoid.
B-I\b7

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +     * @return An {@link InstantCommand} that closes the solenoid.
B-I\b7

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    public DoubleSolenoidSubsystem(Namespace namespace, DoubleSolenoid doubleSolenoid) {
add inverted

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    public DoubleSolenoidSubsystem(String namespaceName, DoubleSolenoid doubleSolenoid) {
add inverted

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    public InstantCommand openSolenoid() {
consider inverted

2023-07-26 10:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    public InstantCommand closeSolenoid() {
consider inverted

2023-07-28 12:06 UTC, Yoel-Perman-Brilliant requested changes

2023-07-28 12:06 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> + * A double solenoid {@link Subsystem}
Take inspiration from `SmartMotorControllerGenericSubsystem`

2023-07-28 12:06 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    private final boolean isInverted;
change to `inverted` and add documentation for it

2023-07-28 12:06 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    public DoubleSolenoidSubsystem(Namespace namespace, DoubleSolenoid doubleSolenoid, boolean isInverted) {
ditto

2023-07-28 12:06 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +    public DoubleSolenoidSubsystem(String namespaceName, DoubleSolenoid doubleSolenoid, boolean isInverted) {
ditto

2023-08-02 15:01 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +     * Checks if the solenoid is inverted.
i think the description is a little unnecessary, not sure

2023-08-09 10:19 UTC, Microsh1t requested changes

2023-08-09 10:19 UTC, Microsh1t commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +        else return new InstantCommand(() -> doubleSolenoid.set(DoubleSolenoid.Value.kReverse));
don't use 'else', just use return.

2023-08-09 10:19 UTC, Microsh1t commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +        else return new InstantCommand(() -> doubleSolenoid.set(DoubleSolenoid.Value.kForward));
don't use 'else', just use return.

2023-08-09 10:19 UTC, Microsh1t commented on src/main/java/com/spikes2212/command/DoubleSolenoidSubsystem.java
> +     * @return an {@link InstantCommand} that opens the solenoid
return **a** link

2023-08-13 08:04 UTC, Yoel-Perman-Brilliant approved these changes

2023-08-13 08:05 UTC, merged