Created LEDS.java
Spikes-2212-Programming-Guild/SpikesLib2 pull request #194
Opened 2023-07-26 08:37 UTC by Spikes-2212

By: Camellia Lami

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant requested changes

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +public class LEDs extends DashboardedSubsystem {
1. Maybe change the name to `AddressableLEDWrapper`
2. Why does it extend `DashboardedSubsystem`?

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +    public LEDs(Namespace namespace, AddressableLED led, AddressableLEDBuffer ledBuffer) {
don't get the leds and the addressable led buffer, instead get the led port and the number of leds and create the objects in the constructor

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +     * Sets the LED strip to a specific color
missing period

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +        setStripColor(color.getRed(), color.getGreen(), color.getBlue());
multiply by a necessary constant?

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +     * Sets a certain range of LEDs to a specific color
missing period

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +        for (int i = start - 1; i < end; i++) {
why `start-1`?

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +    public void setStripColor(int red, int green, int blue) {
Call `setColorInRange` with appropriate parameters.

2023-07-26 11:05 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/LEDs.java
> +    public void configureDashboard() {
delete

2023-07-26 14:12 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/LEDs.java
> +        setStripColor(color.getRed(), color.getGreen(), color.getBlue());
no need

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant requested changes

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +    public AddressableLEDWrapper(int LEDPort, int numberOfLEDs) {
should be `ledPort`

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +    private final AddressableLED led;
briefly explain what each field does (since the difference is not obvious).

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> + * Class that represents a LED strip.
I don't love this documentation but I'm not sure that I have a better idea

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +     * @param red   The desired red value.
B-I\b6, B-I\b7

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +    /**
General method summary?

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +     * @param color The desired {@link Color}.
B-I\b7

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +     * @param red   The desired red value.
![image](https://github.com/Spikes-2212-Programming-Guild/SpikesLib2/assets/87820740/410c037c-434a-44a9-b2a4-31b75638903d)

2023-07-28 12:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +    /**
where general summary?

2023-08-02 14:55 UTC, Yoel-Perman-Brilliant requested changes

2023-08-02 14:55 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +     * {@link AddressableLED} - The LED strip itself.
Each field should have its own documentation (javadoc comments are tied to the things they describe)

2023-08-02 14:55 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +    public void startLed() {
maybe change to `enableStrip()`?

2023-08-02 14:55 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/AddressableLEDWrapper.java
> +    public void stopLed() {
maybe change to `disableStrip()`?

2023-08-09 08:28 UTC, Yoel-Perman-Brilliant requested changes

2023-08-09 08:28 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +public class AddressableLEDWrapper {
ttt

2023-08-09 10:52 UTC, Microsh1t submitted a review, later dismissed

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        led = new AddressableLED(ledPort);
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        ledBuffer = new AddressableLEDBuffer(numberOfLEDs);
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        setColorInRange(red, green, blue, 0, ledBuffer.getLength());
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +            ledBuffer.setRGB(i, red, green, blue);
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        ledBuffer.setRGB(index, red, green, blue);
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        ledBuffer.setRGB(index, color.getRed(), color.getGreen(), color.getBlue());
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        led.setData(ledBuffer);
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        led.start();
always use 'this' to access variables from the current class

2023-08-09 10:52 UTC, Microsh1t commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        led.stop();
always use 'this' to access variables from the current class

2023-08-13 08:10 UTC, Yoel-Perman-Brilliant requested changes

2023-08-13 08:10 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +    /**
this is not how you write doucumentation

2023-08-13 08:10 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +     * {@link AddressableLEDBuffer} - The LED strip's data.
![image](https://github.com/Spikes-2212-Programming-Guild/SpikesLib2/assets/87820740/8ed09c75-1765-47e2-95d0-d546cd227f24)

2023-08-13 08:10 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +     * @param red   the red value
specify the range (0 to 1, 0 to 255, something else)
do it for all the other parameters and relevant constrcutors as well

2023-08-13 08:10 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +    /**
specify to call this periodically

2023-09-21 14:33 UTC, Yoel-Perman-Brilliant approved these changes

2023-09-21 14:35 UTC, Yoel-Perman-Brilliant approved these changes

2023-10-16 14:45 UTC, merged