getRobotPose now uses the correct name and converts the rotation to r…
Spikes-2212-Programming-Guild/SpikesLib2 pull request #201
Opened 2023-10-30 15:12 UTC by TurtleMinecraft

…adians

2023-10-31 07:14 UTC, Yoel-Perman-Brilliant requested changes

2023-10-31 07:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/Limelight.java
> +        double[] result = NetworkTableInstance.getDefault().getTable(name).getEntry("botpose").getDoubleArray(new double[]{});
use `getEntry("botpose").getDoubleArray(...)`

2023-10-31 07:14 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/Limelight.java
> +}
???????

2023-10-31 16:08 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/util/Limelight.java
> +}
!!!!!!!!

2023-11-02 09:00 UTC, Yoel-Perman-Brilliant requested changes

2023-11-09 15:07 UTC, Yoel-Perman-Brilliant approved these changes

2023-11-09 18:26 UTC, merged