Created setVoltage and implemented for tankDrive and arcadeDrive
Spikes-2212-Programming-Guild/SpikesLib2 pull request #207
Opened 2023-11-06 18:33 UTC by Yoel-Perman-Brilliant

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltage.java
> +     * {@link TankDrivetrain} according to speed values from Double {@link Supplier}s for left and right sides.<br>
voltage values

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltage.java
> +     * @param isFinished
where description

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltage.java
> +        this.drivetrain =drivetrain;
A-II\a6

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltage.java
> +    }
A-II\a10

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltage.java
> +        return this.isFinished.get();
why this?????

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithVoltage.java
> + * This command moves a {@link TankDrivetrain} by linear and rotational speeds, using
voltages

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithVoltage.java
> +
?

2023-11-09 17:08 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltage.java
> +public class DriveTankWithVoltage extends CommandBase {
A-II\b3

2023-11-14 11:49 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +        this.drivetrain =drivetrain;
CTRL ALT L

2023-11-14 11:49 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +    }
blank line

2023-11-14 11:49 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +    }
blank line

2023-11-16 14:08 UTC, Spikes-2212 requested changes

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithVoltages.java
> +     * @param drivetrain          the tank drivetrain this command operates on.
remove period

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithVoltages.java
> +     * @param moveValueSupplier   the double {@link Supplier} supplying the linear Voltage. Positive values go forwards.
remove final period

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithVoltages.java
> +     * @param rotateValueSupplier the double {@link Supplier} supplying the rotational Voltage. Positive values go left.
remove final period

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> + * @author Yuval Levy
NO

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> + * A command that moves a {@link TankDrivetrain} using voltage supplied to the left and the right sides independently.
rephrase to be more in line with documentation for other commands

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +public class DriveTankWithVoltages extends CommandBase {
add blank line after this one

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * @param isFinished
???

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * @param drivetrain   the drivetrain this command requires and moves.
remove period

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * @param leftVoltage  the double {@link Supplier} supplying the voltage to move on the right side with.
remove period

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * @param rightVoltage the double {@link Supplier} supplying the voltage to move on the left side with.
remove period

2023-11-16 14:08 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +
delete this blank line

2023-11-16 19:01 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/TankDrivetrain.java
> +     * @param speedLeft the speed to set to the left side (range from -1 to 1). Positive values move this side forward
just -1 to 1, it's more consistent with the rest of the documentations

2023-11-21 10:44 UTC, Spikes-2212 approved these changes

2023-11-21 10:44 UTC, merged