Dev
Spikes-2212-Programming-Guild/SpikesLib2 pull request #211
Opened 2023-11-21 10:57 UTC by Yoel-Perman-Brilliant

2023-11-27 11:30 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/TankDrivetrain.java
> +     * @param leftVoltage  the voltage to the left side (-1 to 1). Positive values move this side forward
-12 to 12

2023-11-27 11:37 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * This constructs a new {@link DriveTankWithVoltages} command that moves the given {@link TankDrivetrain} according to voltage
to the given voltage

2023-11-27 11:38 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * This constructs a new {@link DriveTankWithVoltages} command that moves the given {@link TankDrivetrain} according to voltage
ditto

2023-11-27 11:38 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * This constructs a new {@link DriveTankWithVoltages} command that moves the given {@link TankDrivetrain} according to voltage
ditto

2023-11-27 11:38 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * This constructs a new {@link DriveTankWithVoltages} command that moves the given {@link TankDrivetrain} according to voltage
ditto

2023-11-27 11:45 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/util/Limelight.java
>      public void setLedMode(LedMode mode) {
docs

2023-11-27 14:31 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithVoltages.java
> +     * values for left and right sides. <br>
te

2023-11-27 14:31 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +    default void putCommand(String key, Command command) {
document all and specify that it runs on disable

2023-11-27 14:31 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +    default PIDSettings addPIDNamespace(String name, PIDSettings initialPIDSettings) {
test and document

2023-11-27 14:31 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +    default FeedForwardSettings addFeedForwardNamespace(String name, FeedForwardSettings initialFeedForwardSettings) {
ditto

2023-11-27 14:31 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        setColorInRange(color.getRed(), color.getGreen(), color.getBlue(), start, end);
wrong order

2023-11-27 14:31 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        setColorInRange(red, green, blue, 0, ledBuffer.getLength());
wrong order

2023-11-27 14:31 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        ledBuffer.setRGB(index, red, green, blue);
check order

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithVoltages.java
> +     * Constructs a new {@link DriveArcade} command that moves the given
DriveArcadeWithVoltages!

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a double value to the namespace.
supplier

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds an integer value to the namespace.
ditto

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a string value to the namespace.
ditto

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Can only be changed via the {@link Shuffleboard}, or any other {@link NetworkTable}s UI.
whose value can...

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @param name               the name to be given to the settings
and the child namespace

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> + * A class that handles the communication between an LED strip and the code.
add a note about testing

2023-12-14 20:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +     * Takes the buffer's data and applies it to the LED strip periodically.
should be called periodically

2023-12-18 13:13 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +    default void putCommand(String key, Command command, boolean ignoringDisable) {
runOnDisable

2023-12-18 14:21 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds {@link Sendable} data to the namespace.
Wrong. -5

2023-12-18 14:23 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @param runOnDisable whether the command should be executable when the robot is disabled
this param description is misaligned

2023-12-18 14:25 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a runnable value to the namespace that can be run as a {@link InstantCommand}.
'an InstantCommand' -1

2023-12-18 14:29 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a runnable value that can be run as a {@link InstantCommand} and can run on disable.
'an InstantCommand' -1

2023-12-18 14:32 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a runnable value that can be run as a {@link InstantCommand} and can run on disable.
this wording is inconsistent with other places where you describe the ability of a command to run when the robot is disabled -1

2023-12-18 14:36 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @param initialFeedForwardSettings the feed forward settings to be added
specify that these are the initial values only, similarly to how it was done with the PIDSettings

2023-12-18 14:37 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @return feed forward settings with the most recent value from the network tables
make this consistent with the wording of the previous method's documentation -1

2023-12-18 14:40 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/SpikesLogger.java
> +package com.spikes2212.dashboard;
add an empty line after this

2023-12-18 14:46 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +import java.awt.*;
why import the whole package?

2023-12-18 14:47 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +    private final AddressableLED led;
add an empty line after this one

2023-12-18 14:49 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +     * @param index the index of the LED
reorder these description to match the order of the parameters

2023-12-19 09:22 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @return feed forward settings with the most recent value from the network tables
it literally is????

2023-12-20 14:02 UTC, Spikes-2212 requested changes

2023-12-21 12:17 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/TankDrivetrain.java
>      public TankDrivetrain(MotorController left, MotorController right) {
add a constructor which takes 4 motor controllers; 2 on each side

2023-12-21 12:49 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +public class AddressableLEDWrapper {
add a few functions which make the leds cool (such as advanceLeds)

2023-12-21 14:09 UTC, Spikes-2212 requested changes

2023-12-25 08:05 UTC, Spikes-2212 approved these changes

2023-12-28 14:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +
delete

2023-12-28 14:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +
delete

2023-12-28 14:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @return PID settings with the values from the network tables
uncapitalize

2023-12-28 14:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/SpikesLogger.java
> +     * Creates a default SpikesLogger instance with custom key (name = "SpikesLogger").
a

2023-12-28 14:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/SpikesLogger.java
> +
delete

2023-12-28 14:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/AddressableLEDWrapper.java
> +        for (int i = start; i < end; i++) {
<=

2023-12-28 14:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/Limelight.java
>       * @return the value of the given entry
given key's entry

2023-12-29 22:25 UTC, Spikes-2212 approved these changes

2023-12-29 22:25 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/dashboard/SpikesLogger.java
> + * A logger class meant to be used with the SpikesLogger desktop app to log values from the robot to a computer in real-time.
add link

2024-01-04 14:12 UTC, TurtleMinecraft approved these changes

2024-01-04 14:30 UTC, merged