Fix dev
Spikes-2212-Programming-Guild/SpikesLib2 pull request #213
Opened 2023-11-30 13:26 UTC by TurtleMinecraft

2023-12-07 13:33 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a number value to the namespace.
number supplier

2023-12-07 13:34 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a boolean value to the namespace.
boolean supplier

2023-12-07 13:36 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @return PID settings with the most recent value from the network tables
pid settings with the values from the network tables

2023-12-07 13:37 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a set of {@link PIDSettings} values to the namespace.
to a designated {@link ChildNamespace}

2023-12-07 13:37 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a set of {@link FeedForwardSettings} values to the namespace.
the same comments as on 'addPIDNamespace'

2023-12-07 13:38 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @param initialPIDSettings the PID settings to be added
the initial values for the pid settings

2023-12-07 13:40 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * @param name               the name to be given to the settings
and the child namespace

2023-12-14 15:46 UTC, Yoel-Perman-Brilliant requested changes

2023-12-14 15:46 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Can only be changed via {@link Shuffleboard}.
the, or another {@NetworkTable} UI.

2023-12-14 15:46 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a sendable data to the namespace.
{@link Sendable} data

2023-12-14 15:46 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +     * Adds a runnable value that can run on disable to the namespace.
add the {@InstantCommand} description

2023-12-14 20:03 UTC, Spikes-2212 approved these changes

2023-12-14 20:04 UTC, Yoel-Perman-Brilliant approved these changes

2023-12-14 20:04 UTC, merged