added logWithTimestamp
Spikes-2212-Programming-Guild/SpikesLib2 pull request #220
Opened 2023-12-21 14:16 UTC by Microsh1t

2024-01-11 16:27 UTC, Yoel-Perman-Brilliant requested changes

2024-01-11 16:27 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/dashboard/SpikesLogger.java
> +    public <T> void logWithTimestamp(T output) {
add logWithTimestampCommand

2024-01-19 11:20 UTC, Yoel-Perman-Brilliant-2 approved these changes

2024-01-21 16:37 UTC, Yoel-Perman-Brilliant approved these changes

2024-01-21 16:38 UTC, Yoel-Perman-Brilliant requested changes
test

2024-02-04 18:34 UTC, Yoel-Perman-Brilliant approved these changes

2024-02-04 18:34 UTC, merged