Wpilib24t4est
Spikes-2212-Programming-Guild/SpikesLib2 pull request #227
Opened 2024-01-08 21:38 UTC by TurtleMinecraft

2024-01-09 08:52 UTC, Yoel-Perman-Brilliant commented on build.gradle
> +dependencies {
MERGE

2024-01-09 08:52 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/genericsubsystem/MotoredGenericSubsystem.java
> +        this.motorControllerGroup = new ArrayList<>(motorControllers);
List.of()

2024-01-11 16:22 UTC, Yoel-Perman-Brilliant requested changes

2024-01-11 16:22 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/drivetrains/smartmotorcontrollerdrivetrain/SparkMaxTankDrivetrain.java
potentially make documentations more coherent

2024-01-11 16:22 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/genericsubsystem/MotorControllerGroup.java
> +package com.spikes2212.command.genericsubsystem;
move to util

2024-01-11 16:22 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/genericsubsystem/MotoredGenericSubsystem.java
> +    protected List<MotorController> motorControllers;
if we add back motorControllerGroup, this seems like a pointless change

2024-01-11 16:22 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/state/LayoutManager.java
> +        return new ProxyCommand(allLayouts.get(currentLayout).getCommandForButton(button));
lambda

2024-01-13 09:41 UTC, Yoel-Perman-Brilliant requested changes

2024-01-13 09:41 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/command/genericsubsystem/MotoredGenericSubsystem.java
> +    protected MotorControllerGroup motorControllers;
change type to `MotorController`

2024-01-13 09:41 UTC, Yoel-Perman-Brilliant commented on src/main/java/com/spikes2212/util/MotorControllerGroup.java
> +        return 0.0;
???

2024-01-14 13:49 UTC, Yoel-Perman-Brilliant requested changes

2024-01-14 15:46 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/genericsubsystem/MotoredGenericSubsystem.java
> +    protected MotorController motorControllers;
motorController

2024-01-14 15:48 UTC, Spikes-2212 commented on src/main/java/com/spikes2212/command/genericsubsystem/smartmotorcontrollersubsystem/TalonFXGenericSubsystem.java
> +
remove

2024-01-15 16:36 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/smartmotorcontrollerdrivetrain/SparkMaxTankDrivetrain.java
>  public class SparkMaxTankDrivetrain extends TankDrivetrain implements SmartMotorControllerTankDrivetrain {
add ways to construct instances without providing a namespace name

2024-01-15 16:54 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/genericsubsystem/smartmotorcontrollersubsystem/TalonFXGenericSubsystem.java
> +    protected final List<? extends TalonFX> slaves;
why the wildcard type variable?

2024-01-15 16:58 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/genericsubsystem/smartmotorcontrollersubsystem/TalonFXGenericSubsystem.java
> +    public void configPIDF(PIDSettings pidSettings, FeedForwardSettings feedForwardSettings) {
this method does not apply the configuration it constructs

2024-01-15 16:58 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/genericsubsystem/smartmotorcontrollersubsystem/TalonFXGenericSubsystem.java
> +    public void configureLoop(PIDSettings pidSettings, FeedForwardSettings feedForwardSettings,
neither does this one

2024-01-16 10:01 UTC, Yoel-Perman-Brilliant requested changes

2024-01-16 11:57 UTC, Yoel-Perman-Brilliant approved these changes

2024-01-16 14:43 UTC, Spikes-2212 approved these changes

2024-01-16 14:43 UTC, merged