Gil add izone
Spikes-2212-Programming-Guild/SpikesLib2 pull request #249
Opened 2024-11-12 09:15 UTC by Spikes-2212

2024-11-12 16:03 UTC, TurtleMinecraft requested changes

2024-11-12 16:03 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
>          this.pidController = new PIDController(pidSettings.getkP(), pidSettings.getkI(), pidSettings.getkD());
remove all unnecessary "this" calls

2024-11-12 16:03 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
>          this.leftPIDController.setSetpoint(leftSetpoint.get());
ditto

2024-11-12 16:03 UTC, TurtleMinecraft commented on src/main/java/com/spikes2212/dashboard/Namespace.java
> +        Supplier<Double> iZone = child.addConstantDouble(name + " i zone ", initialPIDSettings.getIZone());
remove space at the end of the string

2024-11-19 17:27 UTC, Yoel-Perman-Brilliant reviewed
Excellent code by Yuval Tal

2025-01-19 14:58 UTC, closed without merging