eren-motion-controllers
Spikes-2212-Programming-Guild/SpikesLib2 pull request #87
Opened 2020-08-26 08:39 UTC by Ergoold

2020-08-26 12:04 UTC, Spikes-2212 commented
Task linked: [CU-7mq4km add a subPackage to control named speedControllers](https://app.clickup.com/t/7mq4km)

2020-08-26 12:04 UTC, Spikes-2212 commented
Task linked: [CU-7mq4gd add SmartMotionSettings](https://app.clickup.com/t/7mq4gd)

2020-08-26 12:04 UTC, Spikes-2212 commented
Task linked: [CU-7mq416 Rename PIDSpeedController to ClosedLoopSpeedController](https://app.clickup.com/t/7mq416)

2020-08-26 12:04 UTC, Spikes-2212 commented
Task linked: [CU-7mq4bk Add SmartMotionSparkMax](https://app.clickup.com/t/7mq4bk)

2020-08-31 06:23 UTC, YuvalLevy1 requested changes

2020-08-31 06:23 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/control/SmartMotionSettings.java
> +     * The minimum velocity of the motor during this smart motion loop.
change the full sentence into a phrase

2020-08-31 07:50 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/control/SmartMotionSettings.java
> +     * The minimum velocity of the motor during this smart motion loop.
This is a short summary, and therefore should consist of full sentences and not a short phrase.

2020-08-31 08:34 UTC, merged