sitton-pidf-talon-motion
Spikes-2212-Programming-Guild/SpikesLib2 pull request #90
Opened 2020-08-26 10:45 UTC by tal-sitton

2020-08-26 12:02 UTC, Spikes-2212 commented
Task linked: [CU-7mq46a Add MotionMagicTalon](https://app.clickup.com/t/7mq46a)

2020-08-26 12:03 UTC, Spikes-2212 commented
Task linked: [CU-7mq4f2 add MotionMagicSettings](https://app.clickup.com/t/7mq4f2)

2020-08-26 12:03 UTC, Spikes-2212 commented
Task linked: [CU-7mq4dd add kF to PIDSettings](https://app.clickup.com/t/7mq4dd)

2020-08-31 06:10 UTC, YuvalLevy1 requested changes

2020-08-31 06:10 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSeetings, int timeout) {
add a second constructor that doesn't recieve a timeout and set the field to 30

2020-08-31 06:10 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public void pidSet(double setpoint) {
call super.pidSet() after setting the motion magic settings

2020-08-31 06:10 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/control/PIDFSettings.java
> +    private Supplier<Double> kF;
move the kF after the kD

2020-08-31 06:10 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/control/PIDTalon.java
> +                throw new Exception("unknown mode");
throw an IllegalArgumentException

2020-08-31 06:34 UTC, tal-sitton commented on src/main/java/com/spikes2212/command/drivetrains/commands/FollowPath.java
> +                      PIDFSettings PIDFSettings, FeedForwardSettings feedForwardSettings, double maxAcceleration,
don't need to change that class

2020-08-31 06:37 UTC, tal-sitton commented on src/main/java/com/spikes2212/command/drivetrains/commands/OrientWithPID.java
> +                         PIDFSettings PIDFSettings, FeedForwardSettings feedForwardSettings) {
I already delete this class

2020-08-31 07:36 UTC, Ergoold requested changes

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
> -    private PIDSettings pidSettings;
make variables use lowerCamelCase

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
>                              FeedForwardSettings rightFeedForwardSettings) {
remove parameters of type FeedForwardSettings

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
>          leftFeedForwardController.setGains(leftFeedForwardSettings.getkS(), leftFeedForwardSettings.getkV(),
remove feedForwardControllers

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
>       * The PID Settings for the PID control loop.
change documentation to reflect the existence of kF in pidfSettings

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
>       * The PID Settings for the turning PID loop.
change documentation to reflect the existence of kF in pidfSettings

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
>       * The PID Settings for the PID loop operating on the left side of the drivetrain.
change documentation to reflect the existence of kF in pidfSettings

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
>       * The PID Settings for the PID loop operating on the right side of the drivetrain.
change documentation to reflect the existence of kF in pidfSettings

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
>       * The last time the subsystem didn't reach target.
add 'the'

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicSettings.java
> +    private Supplier<Integer> targetAcceleration;
rename variable to 'maximumAcceleration'

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDFSettings.java
>          this.kD = kD;
make kF supply 0.0

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +    public PIDSparkMax(CANSparkMax sparkMax, PIDFSettings settings, Supplier<Double> kF, ControlType mode, int timeout) {
remove kF parameter

2020-08-31 07:36 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDSpeedController.java
> +    boolean onTarget(double setpoint) throws Exception;
remove throws clause

2020-08-31 08:28 UTC, Ergoold requested changes

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
> +     * The PIDF Settings for the turning PIDF loop.
change to PID loop

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
> +     * The PIDF Controller for the turning PIDF loop.
change to PID loop

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Settings for the PIDF loop operating on the left side of the drivetrain.
change to PID loop

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Settings for the PIDF loop operating on the right side of the drivetrain.
change to PID loop

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Controller of the PIDF loop operating on the left side of the drivetrain.
change to PID loop

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Controller of the PIDF loop operating on the right side of the drivetrain.
change to PID loop

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
> +                                       PIDFSettings PIDFSettings) {
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSeetings, int timeout) {
rename to mmSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSeetings) {
rename to mmSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
> +    private PIDFSettings PIDFSettings;
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
> +                                       PIDFSettings PIDFSettings) {
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSeetings, int timeout) {
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSeetings) {
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +    private final PIDFSettings settings;
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +    public PIDSparkMax(CANSparkMax sparkMax, PIDFSettings settings, ControlType mode, int timeout) {
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDTalon.java
> +    private final PIDFSettings settings;
rename to pidfSettings

2020-08-31 08:28 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDTalon.java
> +    public PIDTalon(WPI_TalonSRX talon, PIDFSettings settings, ControlMode mode, int timeout) {
rename to pidfSettings

2020-08-31 11:20 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSeetings, int timeout) {
no need

2020-08-31 11:21 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSeetings) {
no need

2020-08-31 11:21 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +    private final PIDFSettings settings;
no need

2020-08-31 11:21 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +    public PIDSparkMax(CANSparkMax sparkMax, PIDFSettings settings, ControlType mode, int timeout) {
no need

2020-08-31 11:22 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDTalon.java
> +    private final PIDFSettings settings;
no need

2020-08-31 11:22 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDTalon.java
> +    public PIDTalon(WPI_TalonSRX talon, PIDFSettings settings, ControlMode mode, int timeout) {
no need

2020-08-31 12:21 UTC, Ergoold requested changes

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Settings for the PIDF loop operating on the left side of the drivetrain.
Change to PID loop

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
> +     * The PIDF Settings for the turning pid loop.
Change to PID loop

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
> +     * The PIDF Controller for the turning pid loop.
Change to PID loop

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Settings for the PIDF loop operating on the right side of the drivetrain.
Change to PID loop

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Controller of the PIDF loop operating on the left side of the drivetrain.
Change to PID loop

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Controller of the PIDF loop operating on the right side of the drivetrain.
Change to PID loop

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
> +     * The last time the subsystem didn't reach the target.
Consider changing to its

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicSettings.java
> +public class MotionMagicSettings {
add class level javadoc

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicSettings.java
> +}
add newline

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +public class MotionMagicTalon extends PIDTalon {
Add class level javadoc

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +     * @param timeout
add parameter description

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSettings, int timeout) {
rename `settings` -> `pidfSettings`

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +    public MotionMagicTalon(WPI_TalonSRX talon, PIDFSettings settings, MotionMagicSettings mmSettings) {
rename `settings` -> `pidfSettings`

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDFSettings.java
> +     * The acceptable distance from the target.
the acceptable distance from the `setpoint`, the `target` is an area that includes the setpoint with a  margin of `tolerance` in both directions

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDFSettings.java
> +    public PIDFSettings(Supplier<Double> kP, Supplier<Double> kI, Supplier<Double> kD, Supplier<Double> tolerance,
call `this`

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDFSettings.java
> +    public PIDFSettings(Supplier<Double> kP, Supplier<Double> kI, Supplier<Double> kD, Supplier<Double> kF, Supplier<Double> tolerance,
reverse constructor order

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDFSettings.java
> +}
blank line at end of file

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +    private final PIDFSettings settings;
rename `settings` -> `pidfSettings`

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +    public PIDSparkMax(CANSparkMax sparkMax, PIDFSettings settings, ControlType mode, int timeout) {
rename `settings` -> `pidfSettings`

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDTalon.java
> +    private final PIDFSettings settings;
rename `settings` -> `pidfSettings`

2020-08-31 12:21 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDTalon.java
> +    public PIDTalon(WPI_TalonSRX talon, PIDFSettings settings, ControlMode mode, int timeout) {
rename `settings` -> `pidfSettings`

2020-08-31 12:59 UTC, YuvalLevy1 requested changes

2020-08-31 12:59 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
> +     * The PIDF Settings for the turning pid loop.
change to PID loop

2020-08-31 12:59 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
> +     * The PIDF Controller for the turning pid loop.
change to PID loop

2020-08-31 12:59 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveArcadeWithPID.java
>       * updates the PIDLoop's setpoint.
add space between PID and Loop's

2020-08-31 12:59 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Controller of the PID loop operating on the left side of the drivetrain.
change to PID Controller

2020-08-31 12:59 UTC, YuvalLevy1 commented on src/main/java/com/spikes2212/command/drivetrains/commands/DriveTankWithPID.java
> +     * The PIDF Controller of the PID loop operating on the right side of the drivetrain.
change PID Controller

2020-08-31 13:16 UTC, Ergoold requested changes

2020-08-31 13:16 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
> +        double svagValue = pidfSettings.getkF();
remove variable svagValue

2020-08-31 13:16 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicSettings.java
> +
remove the blank line between documentation and class declaration

2020-08-31 13:16 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicSettings.java
> +public class MotionMagicSettings {
add blank line after class declaration

2020-08-31 13:16 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicSettings.java
> + * The MotionMagic constants used in a PID loop.
add @author tag

2020-08-31 13:16 UTC, Ergoold commented on src/main/java/com/spikes2212/control/MotionMagicTalon.java
> +     * Constructs a PIDTalon instance with the given parameters as field values.
change documentation to fit MotionMagicTalon

2020-09-02 10:03 UTC, Ergoold requested changes

2020-09-02 10:03 UTC, Ergoold commented on src/main/java/com/spikes2212/control/PIDSparkMax.java
> +     * @param pidfSettings The PID loop's {@link PIDFSettings}.
B-II\c1: Align @param descriptions

2020-09-02 10:21 UTC, Ergoold approved these changes

2020-09-02 10:21 UTC, Ergoold commented on src/main/java/com/spikes2212/command/genericsubsystem/commands/MoveGenericSubsystemWithPID.java
> +     * The last time the subsystem wasn't within its target.
This is a good doc comment - it sounds very natural

2020-09-06 12:12 UTC, closed without merging