fixed conventions of utils and control at least I hope
Spikes-2212-Programming-Guild/SpikesLib2 pull request #96
Opened 2021-11-11 15:15 UTC by Yoel-Perman-Brilliant

2021-11-11 15:26 UTC, Yoel-Perman-Brilliant commented
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2021-11-11 16:18 UTC, tal-sitton requested changes

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/noise/RunningAverageFilter.java
>      private double sum = 0;
add `@author`

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/noise/RunningAverageFilter.java
>      private double sum = 0;
add documentation for `sum`

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/noise/RunningAverageFilter.java
>      private int count = 0;
add documentation for `count`

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
>      public double[] values = new double[3];
add `@author`

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
> +     * calibrates the piegon wrapper based on the yaw sent
the pigeon in general, not specifically the wrapper

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/RepeatCommand.java
remove the redundant `@link`
and use `a commands that...`

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/RepeatCommand.java
add `@author`

2021-11-11 16:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/XboXUID.java
> +    XboxController xbox;
add visibility

2021-11-11 17:26 UTC, tal-sitton requested changes

2021-11-11 17:26 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDSettings.java
> + * @author Ergoold
that's not the author's real name

2021-11-11 17:26 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/noise/NoiseFilter.java
> + */
add class documentation

2021-11-11 17:26 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
> + * @author Simon Kharmatsky
wrong author

2021-11-11 17:26 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/RepeatCommand.java
> + * @author Ergoold
not the author's real name

2021-11-11 17:26 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/XboXUID.java
> + * @author Simon Kharmatsky
wrong author

2021-11-11 18:25 UTC, tal-sitton requested changes

2021-11-11 18:25 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/FeedForwardController.java
> + * @author Simon Kharmatsky
move this below the class' documentation

2021-11-11 18:25 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/FeedForwardSettings.java
> + * @author Simon Kharmatsky
move this below the class' documentation

2021-11-11 18:25 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDSettings.java
> + * @author Eran Goldshtein
move this below the class' documentation

2021-11-11 18:25 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/noise/NoiseFilter.java
> + * @author Simon Kharmatsky
move this below the class' documentation

2021-11-11 18:25 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
> + */
add class documentation

2021-11-11 18:25 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/RepeatCommand.java
> + * @author Eran Gold
move this below the class' documentation

2021-11-11 18:25 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/XboXUID.java
> + */
add class documentation

2021-11-18 14:18 UTC, tal-sitton requested changes

2021-11-18 14:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDSettings.java
> + * The PID constants used in a PIDLoop, and the error tolerance and loop wait time.
PIDLoop doesn't exist

2021-11-18 14:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/FeedForwardController.java
> + * @author Simon Kharmatsky
its Tuval

2021-11-18 14:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
> + * a wrapper class for the pigeon sensor
the `pigeon IMU sensor`

2021-11-18 14:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
> +     * @return the X axis from they gyro
they?

2021-11-18 14:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
> +     * @return the Y axis from they gyro
ditto

2021-11-18 14:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/PigeonWrapper.java
> +     * @return the Z axis from they gyro
ditto

2021-11-18 14:18 UTC, tal-sitton commented on src/main/java/com/spikes2212/util/RepeatCommand.java
misplaced white-space

2021-11-22 19:45 UTC, tal-sitton approved these changes

2021-11-22 19:45 UTC, tal-sitton commented on src/main/java/com/spikes2212/control/PIDSettings.java
> + * The constants used in a PID calculation, and the error tolerance and loop wait time.
too many `and`s in one sentence

2021-11-22 19:46 UTC, tal-sitton requested changes
.

2021-11-22 20:03 UTC, tal-sitton approved these changes

2021-11-23 13:49 UTC, merged